spring:
  application:
    name: person
  datasource:
    url: jdbc:postgresql://localhost:5432/demo
    username: postgres
    password: password
  jpa:
    hibernate:
      ddl-auto: update
      show-sql: true
      properties:
        hibernate:
          format_sql: true
          dialect: org.hibernate.dialect.PostgreSQLDialect

otel:
  sdk:
    disabled: true
  exporter:
    otlp:
      protocol: http/protobuf
      endpoint: https://localhost:4317
      enabled: false

management:
  endpoints:
    web:
      exposure:
        include: "health,info,prometheus"
