spring:
  application:
    name: person
  datasource:
    url: jdbc:postgresql://localhost:5432/demo
    username: postgres
    password: password
  jpa:
    hibernate:
      ddl-auto: update
      show-sql: true
      properties:
        hibernate:
          format_sql: true
          dialect: org.hibernate.dialect.PostgreSQLDialect
logging:
  structured:
    format:
      console: ecs

otel:
  sdk:
    disabled: true

  exporter:
    otlp:
      endpoint: http://localhost:4317
      protocol: grpc
      insecure: true
  instrumentation:
    micrometer:
      enabled: true

management:
  endpoints:
    web:
      exposure:
        include: "health,info,prometheus"
  server:
    port: 9080

server:
  servlet:
    context-path: /
