apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "person.fullname" . }}
  labels:
    {{- include "person.labels" . | nindent 4 }}
data:
  application.yaml: "{{ .Values.properties | toYaml | nindent 2 }}"
