apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "person.fullname" . }}
  labels:
    {{- include "person.labels" . | nindent 4 }}
data:
  SPRING_DATASOURCE_URL: "{{ .Values.properties.spring.datasource.url }}"
  SPRING_DATASOURCE_USERNAME: "{{ .Values.properties.spring.datasource.username }}"
