{{- if .Values.instrumentation.enabled -}}
apiVersion: opentelemetry.io/v1alpha1
kind: Instrumentation
metadata:
  name: {{ include "person.fullname" . }}
spec:
  exporter:
    endpoint: {{ .Values.instrumentation.endpoint }}
  propagators:
    - tracecontext
    - baggage
  sampler:
    type: always_on
    argument: "1"
  java:
    env:
      - name: OTEL_METRICS_EXPORTER
        value: "otlp"
      - name: OTEL_INSTRUMENTATION_MICROMETER_ENABLED
        value: "true"
      - name: "OTEL_INSTRUMENTATION_MICROMETER_DEFAULT_BINDERS_ENABLED"
        value: "true"
      - name: OTEL_INSTRUMENTATION_MICROMETER_LOGGING_ENABLED
        value: "true"
{{- end }}
