{{- if .Values.instrumentation.enabled -}}
apiVersion: opentelemetry.io/v1alpha1
kind: Instrumentation
metadata:
  name: {{ include "person.fullname" . }}
spec:
  exporter:
    endpoint: {{ .Values.instrumentation.endpoint }}
  propagators:
    - tracecontext
    - baggage
  sampler:
    type: always_on
    argument: "1"
{{- end }}
