apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: {{ include "person.fullname" . }}
rules:
  - apiGroups: [""]
    verbs: ["get", "list", "watch"]
    resources: ["configmaps", "pods", "services", "endpoints", "secrets"]
