apiVersion: v1
kind: Secret
metadata:
  name: {{ include "person.fullname" . }}
  labels:
    {{- include "person.labels" . | nindent 4 }}
data:
  application.yaml: "{{ .Values.config | toYaml | nindent 2 | b64enc }}"
