apiVersion: v1
kind: Secret
metadata:
  name: {{ include "person.fullname" . }}
  labels:
    {{- include "person.labels" . | nindent 4 }}
data:
  #  application.yaml: "{{ .Values.secrets | toYaml | nindent 2 | b64enc }}"
  SPRING_DATASOURCE_PASSWORD: "{{ .Values.secrets.spring.datasource.password | b64enc }}"
