{{- if .Values.serviceMonitor.enabled }}
apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: {{ include "person.fullname" . }}
  labels:
    {{- include "person.labels" . | nindent 4 }}
spec:
  selector:
    matchLabels:
      {{- include "person.selectorLabels" . | nindent 6 }}
  endpoints:
  - port: http
    path: /actuator/prometheus
{{- end }}
