apiVersion: v1
kind: Service
metadata:
  name: coredns
  namespace: kube-system
  labels:
    release: coredns
spec:
  internalTrafficPolicy: Cluster
  ports:
    - name: dns
      port: 53
      protocol: UDP
      targetPort: 53
    - name: dns-tcp
      port: 53
      protocol: TCP
      targetPort: 53
    - name: metrics
      port: 9153
      protocol: TCP
      targetPort: 9153
  selector:
    k8s-app: kube-dns
  sessionAffinity: None
  type: ClusterIP
