apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: coredns
  namespace: kube-system
spec:
  endpoints:
  - bearerTokenFile: /var/run/secrets/kubernetes.io/serviceaccount/token
    interval: 15s
    port: metrics
    honorLabels: true
  namespaceSelector:
    matchNames:
    - kube-system
  selector:
    matchLabels:
      release: coredns
