rbac:
  # -- If pspEnabled true, a PodSecurityPolicy is created for K8s that use psp.
  pspEnabled: false
  # -- For OpenShift set pspEnabled to 'false' and sccEnabled to 'true' to use the SecurityContextConstraints.
  sccEnabled: true
rollout_operator:
  podSecurityContext:
    fsGroup: null
    runAsGroup: null
    runAsUser: null
enterpriseGateway:  
  tokengen:
    podSecurityContext:
      fsGroup: null
      runAsGroup: null
      runAsUser: null
adminApi:
  podSecurityContext:
    fsGroup: null
    runAsGroup: null
    runAsUser: null
    runAsNonRoot: true
enterpriseGateway:
  podSecurityContext:
    fsGroup: null
    runAsGroup: null
    runAsUser: null
    runAsNonRoot: true
memcached:
  podSecurityContext:
    fsGroup: null
    runAsGroup: null
    runAsUser: null
    runAsNonRoot: true
gateway:
  podSecurityContext:
    fsGroup: null
    runAsGroup: null
    runAsUser: null
    runAsNonRoot: true
loki:   
  podSecurityContext:
    fsGroup: null
    runAsGroup: null
    runAsUser: null
    runAsNonRoot: true
  commonConfig:
    replication_factor: 1
  schemaConfig:
    configs:
      - from: "2024-04-01"
        store: tsdb
        object_store: s3
        schema: v13
        index:
          prefix: loki_index_
          period: 24h
  pattern_ingester:
    enabled: true
  limits_config:
    allow_structured_metadata: true
    volume_enabled: true
  ruler:
    enable_api: true
  tenant_federation:
    enabled: true  # Enable tenant federation

minio:
  enabled: false
  persistence:
    size: 100Gi

deploymentMode: SingleBinary

singleBinary:
  replicas: 1

# Zero out replica counts of other deployment modes
backend:
  replicas: 0
read:
  replicas: 0
write:
  replicas: 0

ingester:
  replicas: 0
querier:
  replicas: 0
queryFrontend:
  replicas: 0
queryScheduler:
  replicas: 0
distributor:
  replicas: 0
compactor:
  replicas: 0
indexGateway:
  replicas: 0
bloomCompactor:
  replicas: 0
bloomGateway:
  replicas: 0

chunksCache:
  enabled: false
