ingress:
  enabled: true
  annotations:
    cert-manager.io/cluster-issuer: letsencrypt-traefik
  hosts:
    - host: dummy
      paths:
        - path: /
          pathType: ImplementationSpecific
  tls:
    - secretName: person-tls
      hosts:
        - dummy

image:
  pullPolicy: Always

serviceMonitor:
  enabled: true

properties:
  otel:
    sdk:
      disabled: false
    exporter:
      otlp:
        protocol: grpc
        endpoint: http://opentelemetry-collector.observability:4317
        enabled: true
