ingress:
  enabled: true
  annotations:
    cert-manager.io/cluster-issuer: letsencrypt-traefik
  hosts:
    - host: dummy
      paths:
        - path: /
          pathType: ImplementationSpecific
  tls:
    - secretName: person-tls
      hosts:
        - dummy

image:
  pullPolicy: Always

serviceMonitor:
  enabled: true
  portName: actuator
  portNumber: 9080

#    - name: OTEL_INSTRUMENTATION_MICROMETER_ENABLED
#      value: "true"
#    - name: OTEL_INSTRUMENTATION_MICROMETER_DEFAULT_BINDERS_ENABLED
#      value: "true"
#    - name: OTEL_INSTRUMENTATION_MICROMETER_LOGGING_ENABLED
config:
  spring:
    application:
      name: person
  otel:
    service:
      name: person
    sdk:
      disabled: false
    instrumentation:
      micrometer:
        enabled: true
      default:
        binders:
          enabled: true
      logging:
        enabled: true
    metrics:
      exporter: otlp
    exporter:
      otlp:
        endpoint: http://opentelemetry-collector.observability:4317
        insecure: true
        protocol: grpc
  server:
    tomcat:
      accesslog:
        enabled: true
        prefix: stdout
  management:
    otlp:
      metrics:
        export:
          url: http://opentelemetry-collector.observability:4318/v1/metrics
