ingress:
  enabled: true
  annotations:
    cert-manager.io/cluster-issuer: letsencrypt-traefik
  hosts:
    - host: dummy
      paths:
        - path: /person
          pathType: ImplementationSpecific
  tls:
    - secretName: person-tls
      hosts:
        - dummy

image:
  pullPolicy: Always

serviceMonitor:
  enabled: true

config:
  otel:
    sdk:
      disabled: false
    exporter:
      otlp:
        protocol: grpc
        endpoint: http://opentelemetry-collector.observability:4317
  logging:
    structured:
      format:
        console: ecs
    pattern:
      level: trace_id=%mdc{trace_id} span_id=%mdc{span_id} trace_flags=%mdc{trace_flags} %5p
  server:
    tomcat:
      accesslog:
        enabled: true
        prefix: stdout
    servlet:
      context-path: /person
