ingress:
  enabled: true
  annotations:
    cert-manager.io/cluster-issuer: letsencrypt-traefik
  hosts:
    - host: dummy
      paths:
        - path: /
          pathType: ImplementationSpecific
  tls:
    - secretName: person-tls
      hosts:
        - dummy
