ingress:
  enabled: true
  annotations:
    cert-manager.io/cluster-issuer: letsencrypt-traefik
  hosts:
    - host: dummy
      paths:
        - path: /person
          pathType: ImplementationSpecific
  tls:
    - secretName: person-tls
      hosts:
        - dummy

image:
  pullPolicy: Always

serviceMonitor:
  enabled: true
  portName: actuator
  portNumber: 9080

config:
  otel:
    sdk:
      disabled: false
    exporter:
      otlp:
        protocol: grpc
        endpoint: http://opentelemetry-collector.observability:4317
  server:
    tomcat:
      accesslog:
        enabled: true
        prefix: stdout
    servlet:
      context-path: /person
