fullnameOverride: petclinic
ingress:
  enabled: true
  annotations:
    cert-manager.io/cluster-issuer: letsencrypt-traefik
  hosts:
    - host: dummy
      paths:
        - path: /
          pathType: ImplementationSpecific
  tls:
    - secretName: petclinic-tls
      hosts:
        - dummy

image:
  pullPolicy: Always

serviceMonitor:
  enabled: true
  portName: actuator
  portNumber: 9080

config:
  spring:
    application:
      name: petclinic
    profiles:
      active: postgres
  logging:
    level:
      root: INFO
      org:
        springframework:
          web: DEBUG
    structured:
      format:
        console: ecs
    pattern:
      level: trace_id=%mdc{trace_id} span_id=%mdc{span_id} trace_flags=%mdc{trace_flags} %5p
  server:
    tomcat:
      accesslog:
        enabled: true
        prefix: stdout
  management:
    server:
      port: 9080
    metrics:
      export:
        prometheus:
          enabled: true
    endpoints:
      web:
        exposure:
          include: "*"
    prometheus:
      metrics:
        export:
          enabled: true
  otel:
    exporter:
      logging:
        enabled: true
    metrics:
      exporter: otlp
    instrumentation:
      micrometer:
        enabled: false
      logback-appender:
        experimental:
          capture-mdc-attributes: "*"

instrumentation:
  enabled: true
  endpoint: http://opentelemetry-collector.observability:4318/

env:
  - name: OTEL_INSTRUMENTATION_MICROMETER_ENABLED
    value: "true"
