tempo:
  persistence:
    enabled: true
    size: 100Gi

#global_overrides:
#  metrics_generator_processors:
#    - service-graphs
#    - span-metrics

overrides:
  defaults:
    global:
      max_bytes_per_trace: 50000000
      # max_search_bytes_per_trace: 50000000
    metrics_generator:
      processors:
        - service-graphs
        - span-metrics
        - local-blocks


metricsGenerator:
  enabled: true
  config:
    storage:
      remote_write:
        - url: http://mimir-nginx.observability-mimir/api/v1/push
          send_exemplars: true
          headers:
            X-Scope-OrgID: "1"
    processor:
      service_graphs:
        dimensions: []
      span_metrics:
        enable_target_info: true
        dimensions:
          - "http.status.code"
          - "http.method"
          - "enduser.id"
          - "client.address"
          - "geo.country_name"
          - "geo.city_name"
          - "geo.continent_code"
          - "geo.country_code"
          - "geo.country_iso_code"
          - "geo.location.lat"
          - "geo.location.lon"
  persistence:
    enabled: true
    size: 10Gi
    storageClass: managed

ingester:
  persistence:
    enabled: true
    size: 100Gi
    storageClass: azurefile

distributor:
  autoscaling:
    enabled: true

querier:
  autoscaling:
    enabled: true

queryFrontend:
  autoscaling:
    enabled: true

traces:
  otlp:
    grpc:
      # Enable gRPC port for OTLP on port 4317
      enabled: true

securityContext:
  fsGroup: null
  runAsGroup: null
  runAsUser: null
  runAsNonRoot: true